import { jsPDF } from "jspdf";

export async function generateAssignmentPDF(
    name: string,
    rollNo: string,
    batch: string,
    solutionText: string
) {
    const doc = new jsPDF();

    // Settings
    const margin = 20;
    let yPosition = 20;
    const pageWidth = doc.internal.pageSize.getWidth();

    // Header section
    doc.setFontSize(22);
    doc.setTextColor(59, 130, 246); // Primary blue color
    doc.text("Digital Design Assignment", margin, yPosition);
    yPosition += 15;

    // Student Details Box
    doc.setDrawColor(200, 200, 200);
    doc.setFillColor(245, 245, 245);
    doc.roundedRect(margin, yPosition, pageWidth - margin * 2, 40, 3, 3, "FD");

    doc.setFontSize(12);
    doc.setTextColor(30, 41, 59); // Dark slate
    doc.setFont("helvetica", "bold");
    doc.text("Student Details", margin + 5, yPosition + 10);

    doc.setFont("helvetica", "normal");
    doc.text(`Name: ${name}`, margin + 5, yPosition + 20);
    doc.text(`Roll Number: ${rollNo}`, margin + 5, yPosition + 28);
    doc.text(`Batch/Section: ${batch}`, margin + pageWidth / 2, yPosition + 20);
    yPosition += 50;

    // Solution Section Title
    doc.setFontSize(16);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(15, 23, 42); // slate-900
    doc.text("Assignment Solutions", margin, yPosition);
    yPosition += 8;

    doc.setDrawColor(59, 130, 246);
    doc.setLineWidth(1);
    doc.line(margin, yPosition, pageWidth - margin, yPosition);
    yPosition += 15;

    // Solution Content
    doc.setFontSize(11);

    // Process text line by line to add basic styling based on content
    const rawLines = solutionText.split('\n');

    rawLines.forEach((rawLine) => {
        // Handle long lines that need wrapping
        const wrappedLines = doc.splitTextToSize(rawLine, pageWidth - margin * 2);

        wrappedLines.forEach((line: string) => {
            if (yPosition > doc.internal.pageSize.getHeight() - margin - 15) {
                doc.addPage();
                yPosition = margin + 10;
            }

            // Quick formatting check
            if (line.trim().toUpperCase().startsWith("QUESTION")) {
                doc.setFont("helvetica", "bold");
                doc.setTextColor(59, 130, 246); // Blue
                yPosition += 5; // Extra space before question
            } else if (line.trim().toUpperCase().startsWith("SOLUTION")) {
                doc.setFont("helvetica", "bold");
                doc.setTextColor(16, 185, 129); // Emerald Green
            } else {
                doc.setFont("helvetica", "normal");
                doc.setTextColor(51, 65, 85); // Slate 700
            }

            doc.text(line, margin, yPosition);
            yPosition += 7; // Line height
        });
    });

    // Footer Message
    if (yPosition > doc.internal.pageSize.getHeight() - margin - 20) {
        doc.addPage();
        yPosition = margin;
    }
    yPosition += 15;
    doc.setFontSize(10);
    doc.setFont("helvetica", "italic");
    doc.setTextColor(150, 150, 150);
    doc.text(
        `Generated by Quubit Digital Design Solver @ ${new Date().toLocaleDateString()}`,
        margin,
        yPosition
    );

    // Save PDF
    doc.save(`${rollNo}_Digital_Design_Assignment.pdf`);
}
